---
name: Run PostgreSQL Regression Tests

on: [push, workflow_dispatch]

jobs:
  pg-regression:

    runs-on: ubuntu-latest

    steps:
      - name: install postgres build dependencies
        run: |
          sudo apt-get install -y bison flex zlib1g zlib1g-dev pkg-config \
            libssl-dev libreadline-dev

      - name: checkout postgres repo
        uses: actions/checkout@v2
        with:
          repository: postgres/postgres
          path: postgres

      - name: configure postgres build
        run: |
          cd postgres
          ./configure --prefix=${HOME}/pgsql --with-python --with-openssl

      - name: build and install postgres
        run: |
          cd postgres
          make
          make install

      - name: ls
        run: |
          ls -al
          echo ${PWD}
          echo ${HOME}
