---
name: Run PostgreSQL Regression Tests

on: [push, workflow_dispatch]

jobs:
  pg-regression:

    runs-on: ubuntu-latest

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y bison flex zlib1g zlib1g-dev pkg-config \
            libssl-dev libreadline-dev libtool cmake automake autoconf make \
            ninja-build curl unzip virtualenv openjdk-11-jdk build-essential \
            libc++1
          mkdir -p ${HOME}/bin/clang10
          cd ${HOME}/bin/clang10
          wget -q https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
          tar -xf clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz \
            --strip-components 1
          export PATH=${HOME}/bin/clang10/bin:$PATH

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Checkout postgres repository
        uses: actions/checkout@v2
        with:
          repository: postgres/postgres
          path: postgres
          fetch-depth: 2

      - name: Configure PostgreSQL build
        run: |
          cd postgres
          ./configure --prefix=/tmp/pgsql --with-python --with-openssl

      - name: Build and install PostgreSQL
        run: |
          cd postgres
          make -j4 install
          make -j4 -C contrib install

      - name: Create new PostgreSQL cluster
        run: |
          mkdir /tmp/data
          chmod 0700 /tmp/data
          /tmp/pgsql/bin/initdb -D /tmp/data -A trust
          /tmp/pgsql/bin/pg_ctl -D /tmp/data -l /tmp/data/postgresql.log start

      - name: Checkout EnvoyProxy repository
        uses: actions/checkout@v2
        with:
          repository: cpakulski/envoy
          ref: 10942_1
          path: envoy
          fetch-depth: 2

      - name: Build EnvoyProxy
        run: |
          ls -al && ls -al bin && ls -al bin/clang10
          export PATH=${HOME}/bin/clang10/bin:$PATH
          cd envoy
          bazel/setup_clang.sh ${HOME}/bin/clang10
          bazelisk shutdown
          bazelisk build -c fastbuild --spawn_strategy=local \
            --discard_analysis_cache --nouse_action_cache --config clang \
            --config libc++ //source/exe:envoy-static

      - name: Run PostgreSQL regression tests
        run: |
          bash -x run-postgres-regression.bash
