---
name: Run PostgreSQL Regression Tests

on: [workflow_dispatch]

jobs:
  pg-regression:

    runs-on: ubuntu-latest

    steps:
      - name: install postgres build dependencies
        run: |
          sudo apt-get install -y bison flex zlib1g zlib1g-dev pkg-config \
            libssl-dev libreadline-dev

      - name: checkout postgres repo
        uses: actions/checkout@v2
        with:
          repository: postgres/postgres
          path: postgres

      - name: configure postgres build
        run: |
          cd postgres
          ./configure --prefix=./pgsql --with-python --with-openssl

      - name: build and install postgres
        run: |
          cd postgres
          make
          make install

      - name: create new cluster
        run: |
          mkdir data
          chmod 0700 data
          ./pgsql/bin/initdb -D data
          ./pgsql/bin/pg_ctl -D data -l data/postgresql.log start
          ps faux | grep postgres

      - name: ls
        run: |
          ls -al
          echo ${PWD}
          echo ${HOME}
          ls -al ${HOME}
