---
name: Run PostgreSQL Regression Tests

on: [push, workflow_dispatch]

jobs:
  pg-regression:

    runs-on: ubuntu-latest

    steps:
      - name: install postgres and envoyproxy build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y bison flex zlib1g zlib1g-dev pkg-config \
            libssl-dev libreadline-dev libtool cmake automake autoconf make \
            ninja-build curl unzip virtualenv openjdk-11-jdk build-essential \
            libc++1
          mkdir -p bin/clang10
          cd bin/clang10
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
          tar -xf clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz \
            --strip-components 1
          export PATH=bin/clang10/bin:$PATH

      - name: checkout postgres repo
        uses: actions/checkout@v2
        with:
          repository: postgres/postgres
          path: postgres

      - name: configure postgres build
        run: |
          cd postgres
          ./configure --prefix=/tmp/pgsql --with-python --with-openssl

      - name: build and install postgres
        run: |
          cd postgres
          make -j4 install
          make -j4 -C contrib install

      - name: create new cluster
        run: |
          mkdir /tmp/data
          chmod 0700 /tmp/data
          /tmp/pgsql/bin/initdb -D /tmp/data -A trust
          /tmp/pgsql/bin/pg_ctl -D /tmp/data -l /tmp/data/postgresql.log start

      - name: checkout envoyproxy repo
        uses: actions/checkout@v2
        with:
          repository: envoyproxy/envoy
          path: envoy

      - name: build envoyproxy
        run: |
          ls -al && ls -al bin && ls -al bin/clang10
          export PATH=bin/clang10/bin:$PATH
          cd envoy
          bazel/setup_clang.sh ../bin/clang10
          bazelisk shutdown
          bazelisk build -c fastbuild --spawn_strategy=local \
            --discard_analysis_cache --nouse_action_cache --config clang \
            --config libc++ //source/exe:envoy-static

      - name: run postgres regression tests
        run: |
          cd postgres
          PGPORT=5432 make installcheck
          PGPORT=5432 make -C contrib installcheck

      - name: ls
        run: |
          ls -al
          ls -al ..
          ls -al ${HOME}
